import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { AppNavigationMenu, AppButton, AppHeader } from "@workspace/ui/components";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-background text-foreground font-sans`}
      >
        <Providers>
          <div className="min-h-screen flex flex-col">
            <AppHeader
              navItems={[
                { label: "Dashboard", href: "/" },
                { label: "Markets", href: "/markets" },
                { label: "Governance", href: "/governance" },
              ]}
              activeHref="/"
              className="mb-6"
              actions={
                <AppButton variant="secondary" size="sm">
                  Connect Wallet
                </AppButton>
              }
            />

            <main className="max-w-[1200px] mx-auto w-full px-4 flex-1">
              {children}
            </main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
